### ISSUE TITLE
Proposal to Draft a Privacy Policy, About Us and FAQ 

### ISSUE THREAD

**Issue by Pope19** [TimothyMee/steem-sport#1]
Greetings,

I am a copywriter, and have contributed to many App and Platforms using my writing skills.

A privacy policy is a document that states an App/site potential collection/use of visitors /users data.
About us normally found on the landing page gives a brief description of the of the App while FAQ help users with quick answers to their potential questions.

I am willing to contribute to the development and stability of your platform through documentation some of which will provide you with legal indemnity.

Your response is anticipated.

Thank you.

@pope1995 on steemit
@pope1995#6757 on discord

**Comment by TimothyMee** [comment]
Hey..  I liked the idea... So how do you do it..
How may I help

**Comment by Pope19** [comment]
Just tell me about steemsport here and how to login. 

You can contact me on discord @Pope1995#6757

**Comment by TimothyMee** [comment]
Oh aii.. Its still in development but. steem-sports is a app that serves as
a wrapper for steemit's sport community (think of it as an app for sport
bloggers on steemit).

So sport stories can be viewed on this app, written/posted on the app
(which in turn is posted to steemit), upvoted and commented on.

The goal is to make a sport app for steemit to make it easier for both
sport writers and sport lovers to access this.

So that a summary of the app really.

No need to login. the app will be using the secured SteemConnect to post and access other information..

**Comment by TimothyMee** [comment]
Cheers
